#!/usr/bin/env python3

import os
import sys
import json
import emails
import locale
import reports

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])

def return_max(years):
  k = list(years.keys())
  v = list(years.values())
  return k[v.index(max(v))]

def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0}
  car_years = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # Find car with max sales
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item
    # Generate a dict of car years and their total count
    car_years[item["car"]["car_year"]] = car_years.get(item["car"]["car_year"], 0) + item["total_sales"]

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(
      format_car(max_sales["car"]), max_sales["total_sales"]),
    "The most popular year was {} with {} sales.".format(
      return_max(car_years), car_years[return_max(car_years)])
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def summary_str(summary, br):
  body = ""
  for item in summary:
    body += str(item) + br
  return body


def send_email(summary):
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = summary_str(summary, "\n")
  message = emails.generate(sender, receiver, subject, body, "/tmp/report.pdf")
  emails.send(message)


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  table_data = cars_dict_to_table(data)
  reports.generate("/tmp/report.pdf", "Sales summary for last month", summary_str(summary, "<br/>"), table_data)
  send_email(summary)
  print("Email sent")


if __name__ == "__main__":
  main(sys.argv)
